name: Docker Image CI

on:
  push:
    branches: [ "master" , "update_version"]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag scotlandshine/shiny-shine:$(date +%s)
