on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: shinytest

# env:
#   RENV_PATHS_ROOT: '%LOCALAPPDATA%/R/cache/R/renv'

jobs:
  shinytest:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - name: Set RENV_PATHS_ROOT
        shell: bash
        run: |
          echo "RENV_PATHS_ROOT=${{ runner.temp }}/renv" >> $GITHUB_ENV
          
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: 4.3.1
          
      - name: Cache packages
        uses: actions/cache@v3
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      
      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      - name: Install shinytest deps
        run: shinytest::installDependencies()
        shell: Rscript {0}

      - name: Run app tests
        run: R -f run_tests.R
