on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: shinytest

jobs:
  shinytest:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install shinytest
        run:
            install.packages("shinytest"); shinytest::installDependencies()
        shell: Rscript {0}

      - name: Test app directory
        run: shinytest::testApp("app")
        shell: Rscript {0}
